# fly.toml app configuration file generated for puhelinluettelo-lauri on 2023-06-14T22:02:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "puhelinluettelo-lauri"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
