on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  scheduled_check:
    if: ${{ false }}
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
            url: https://puhelinluettelo-lauri.fly.dev